---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, cvs on gcp, anf, azure netapp files 
summary: Consulte as opções de configuração disponíveis para suas configurações do Astra Trident. 
---
= Opções de configuração de armazenamento
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Consulte as opções de configuração disponíveis para suas configurações do Astra Trident.



== Opções de configuração global

Essas opções de configuração se aplicam a todas as configurações do Astra Trident, independentemente da plataforma de storage usada.

[cols="3*"]
|===
| Opção | Descrição | Exemplo 


| `version`  a| 
Número da versão do ficheiro de configuração
 a| 
1



| `storageDriverName`  a| 
Nome do driver de armazenamento
 a| 
`ontap-nas` `ontap-san`, , `ontap-nas-economy`
`ontap-nas-flexgroup` , `solidfire-san`, , , `azure-netapp-files`, ou `gcp-cvs`



| `storagePrefix`  a| 
Prefixo opcional para nomes de volume. Padrão: "Netappdvp_".
 a| 
estadiamento_



| `limitVolumeSize`  a| 
Restrição opcional nos tamanhos de volume. Padrão: "" (não aplicado)
 a| 
13 10 g

|===

TIP: Não use `storagePrefix` (incluindo o padrão) para backends de elemento. Por padrão, o `solidfire-san` driver ignorará essa configuração e não usará um prefixo. Recomendamos usar um tenantID específico para mapeamento de volume do Docker ou usar os dados de atributo que são preenchidos com a versão do Docker, informações de driver e nome bruto do Docker nos casos em que qualquer nome munging pode ter sido usado.

As opções padrão estão disponíveis para evitar ter que especificá-las em cada volume criado. A `size` opção está disponível para todos os tipos de controlador. Consulte a seção Configuração do ONTAP para obter um exemplo de como definir o tamanho padrão do volume.

[cols="3*"]
|===
| Opção | Descrição | Exemplo 


| `size`  a| 
Tamanho padrão opcional para novos volumes. Padrão: "1G"
 a| 
10G

|===


== Configuração ONTAP

Além dos valores de configuração global acima, ao usar o ONTAP, as seguintes opções de nível superior estão disponíveis.

[cols="3*"]
|===
| Opção | Descrição | Exemplo 


| `managementLIF`  a| 
Endereço IP do ONTAP Management LIF. Você pode especificar um nome de domínio totalmente qualificado (FQDN).
 a| 
10.0.0.1



| `dataLIF`  a| 
Endereço IP do protocolo LIF; será derivado se não for especificado. Para os `ontap-nas` drivers *somente*, você pode especificar um FQDN, caso em que o FQDN será usado para as operações de montagem NFS. Para os `ontap-san` drivers, o padrão é usar todos os IPs de LIF de dados da SVM e usar multipath iSCSI. Especificar um endereço IP para `dataLIF` os `ontap-san` drivers força o driver a desabilitar o multipath e usar apenas o endereço especificado.
 a| 
10.0.0.2



| `svm`  a| 
Máquina virtual de armazenamento a utilizar (necessária, se o LIF de gestão for um LIF de cluster)
 a| 
svm_nfs



| `username`  a| 
Nome de utilizador para ligar ao dispositivo de armazenamento
 a| 
vsadmin



| `password`  a| 
Palavra-passe para ligar ao dispositivo de armazenamento
 a| 
segredo



| `aggregate`  a| 
Agregado para provisionamento (opcional; se definido, deve ser atribuído ao SVM). Para `ontap-nas-flexgroup` o driver, essa opção é ignorada. Todos os agregados atribuídos ao SVM são usados para provisionar um volume FlexGroup.
 a| 
aggr1



| `limitAggregateUsage`  a| 
Opcional, falha no provisionamento se o uso estiver acima dessa porcentagem
 a| 
75%



| `nfsMountOptions`  a| 
Controle refinado das opções de montagem NFS; o padrão é "-o nfsvers 3". *Disponível apenas para os `ontap-nas` condutores e `ontap-nas-economy`*. https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["Consulte as informações de configuração do host NFS aqui"^].
 a| 
-o nfsvers 4



| `igroupName`  a| 
O igroup usado pelo plugin; o padrão é "netappdvp". *Disponível apenas para o rio ONTAP-san*.
 a| 
miigrupo



| `limitVolumeSize`  a| 
Tamanho máximo do volume requestable e tamanho do volume pai de qtree. *Para o `ontap-nas-economy` driver, essa opção limita adicionalmente o tamanho dos FlexVols que ele cria*.
 a| 
13 300 g



| `qtreesPerFlexvol`  a| 
Qtrees máximos por FlexVol, tem de estar no intervalo [50, 300], o padrão é 200. *Para `ontap-nas-economy` o driver, esta opção permite personalizar o número máximo de qtrees por FlexVol*.
 a| 
300

|===
As opções padrão estão disponíveis para evitar ter que especificá-las em cada volume criado:

[cols="3*"]
|===
| Opção | Descrição | Exemplo 


| `spaceReserve`  a| 
Modo de reserva de espaço; "nenhum" (thin Provisioning) ou "volume" (thick)
 a| 
nenhum



| `snapshotPolicy`  a| 
A política do Snapshot a ser usada, o padrão é "nenhum"
 a| 
nenhum



| `snapshotReserve`  a| 
O padrão é "" para aceitar o padrão do ONTAP
 a| 
10



| `splitOnClone`  a| 
Dividir um clone de seu pai na criação, o padrão é "falso"
 a| 
falso



| `encryption`  a| 
Ativa a criptografia de volume NetApp (NVE) no novo volume; o padrão é `false`. O NVE deve ser licenciado e habilitado no cluster para usar essa opção.

Se o NAE estiver ativado no back-end, qualquer volume provisionado no Astra Trident será o NAE ativado.

Para obter mais informações, consulte: link:../trident-reco/security-reco.html["Como o Astra Trident funciona com NVE e NAE"].
 a| 
verdadeiro



| `unixPermissions`  a| 
Opção nas para volumes NFS provisionados, o padrão é "777"
 a| 
777



| `snapshotDir`  a| 
Opção nas para acesso ao `.snapshot` diretório, o padrão é "false"
 a| 
verdadeiro



| `exportPolicy`  a| 
A opção nas para a política de exportação NFS usar, o padrão é "padrão"
 a| 
padrão



| `securityStyle`  a| 
Opção nas para acesso ao volume NFS provisionado, o padrão é "UNIX"
 a| 
misto



| `fileSystemType`  a| 
Opção SAN para selecionar o tipo de sistema de arquivos, o padrão é "ext4"
 a| 
xfs



| `tieringPolicy`  a| 
A política de disposição em categorias a ser usada, o padrão é "nenhuma"; "somente snapshot" para configuração pré-ONTAP 9.5 SVM-DR
 a| 
nenhum

|===


=== Opções de dimensionamento

Os `ontap-nas` drivers e `ontap-san` criam um ONTAP FlexVol para cada volume do Docker. O ONTAP dá suporte a até 1000 FlexVols por nó de cluster com um máximo de cluster de 12.000 FlexVols. Se os requisitos de volume do Docker se ajustarem a essa limitação, `ontap-nas` o driver será a solução nas preferida devido aos recursos adicionais oferecidos pelo FlexVols, como snapshots Docker volume granular e clonagem.

Se você precisar de mais volumes do Docker do que pode ser acomodado pelos limites do FlexVol, escolha o `ontap-nas-economy` ou o `ontap-san-economy` driver.

 `ontap-nas-economy`O driver cria volumes do Docker como Qtrees do ONTAP em um pool de FlexVols gerenciados automaticamente. As Qtrees oferecem dimensionamento muito maior, até 100.000 PB por nó de cluster e 2.400.000 PB por cluster, à custa de alguns recursos.  `ontap-nas-economy`O driver não oferece suporte a snapshots ou clonagem granular de volume do Docker.


NOTE: No momento, o `ontap-nas-economy` driver não é compatível com o Docker Swarm, porque o Swarm não orquestra a criação de volume em vários nós.

 `ontap-san-economy`O driver cria volumes do Docker como LUNs ONTAP em um pool compartilhado de FlexVols gerenciados automaticamente. Dessa forma, cada FlexVol não se restringe a apenas um LUN e oferece melhor escalabilidade para workloads SAN. Dependendo do storage array, o ONTAP oferece suporte para até 16384 LUNs por cluster. Como os volumes são LUNs abaixo, esse driver oferece suporte a snapshots e clonagem granular do Docker volume.

Escolha o `ontap-nas-flexgroup` driver para aumentar o paralelismo para um único volume que pode crescer para o intervalo de petabytes com bilhões de arquivos. Alguns casos de uso ideais para FlexGroups incluem IA/ML/DL, big data e análise, compilações de software, streaming, repositórios de arquivos e assim por diante. O Trident usa todos os agregados atribuídos a uma SVM ao provisionar um volume FlexGroup. O suporte do FlexGroup no Trident também tem as seguintes considerações:

* Requer ONTAP versão 9,2 ou superior.
* A partir desta redação, FlexGroups só suportam NFS v3.
* Recomendado para ativar os identificadores NFSv3 de 64 bits para o SVM.
* O tamanho mínimo recomendado de FlexGroup é 100GB.
* A clonagem não é compatível com volumes FlexGroup.


Para obter informações sobre FlexGroups e cargas de trabalho apropriadas para FlexGroups, consulte https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["Guia de práticas recomendadas e implementação de volumes do NetApp FlexGroup"^].

Para obter recursos avançados e grande escala no mesmo ambiente, você pode executar várias instâncias do Docker volume Plugin, com uma usando `ontap-nas` e outra usando `ontap-nas-economy`o .



=== Exemplo de arquivos de configuração do ONTAP

*Exemplo de NFS para `ontap-nas` driver*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "secret",
    "aggregate": "aggr1",
    "defaults": {
      "size": "10G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
*Exemplo de NFS para `ontap-nas-flexgroup` driver*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-flexgroup",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "secret",
    "defaults": {
      "size": "100G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
*Exemplo de NFS para `ontap-nas-economy` driver*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "secret",
    "aggregate": "aggr1"
}
----
*Exemplo iSCSI para `ontap-san` driver*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi",
    "username": "vsadmin",
    "password": "secret",
    "aggregate": "aggr1",
    "igroupName": "myigroup"
}
----
*Exemplo de NFS para `ontap-san-economy` driver*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi_eco",
    "username": "vsadmin",
    "password": "secret",
    "aggregate": "aggr1",
    "igroupName": "myigroup"
}
----


== Configuração do software Element

Além dos valores de configuração global, ao usar o software Element (NetApp HCI/SolidFire), essas opções estão disponíveis.

[cols="3*"]
|===
| Opção | Descrição | Exemplo 


| `Endpoint`  a| 
/<login>:<password>/<mvip>/json-rpc/<element-version>
 a| 
\https://admin:admin@192.168.160.3/json-rpc/8.0



| `SVIP`  a| 
Endereço IP iSCSI e porta
 a| 
10,0.0,7:3260



| `TenantName`  a| 
Locatário do SolidFireF para usar (criado se não for encontrado)
 a| 
"docker"



| `InitiatorIFace`  a| 
Especifique a interface ao restringir o tráfego iSCSI a uma interface não predefinida
 a| 
"padrão"



| `Types`  a| 
Especificações de QoS
 a| 
Veja o exemplo abaixo



| `LegacyNamePrefix`  a| 
Prefixo para instalações Trident atualizadas. Se você usou uma versão do Trident anterior a 1.3.2 e fez uma atualização com volumes existentes, precisará definir esse valor para acessar seus volumes antigos que foram mapeados pelo método de nome de volume.
 a| 
"netappdvp-"

|===
O `solidfire-san` driver não suporta Docker Swarm.



=== Exemplo de arquivo de configuração de software Element

[listing]
----
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
    "SVIP": "10.0.0.7:3260",
    "TenantName": "docker",
    "InitiatorIFace": "default",
    "Types": [
        {
            "Type": "Bronze",
            "Qos": {
                "minIOPS": 1000,
                "maxIOPS": 2000,
                "burstIOPS": 4000
            }
        },
        {
            "Type": "Silver",
            "Qos": {
                "minIOPS": 4000,
                "maxIOPS": 6000,
                "burstIOPS": 8000
            }
        },
        {
            "Type": "Gold",
            "Qos": {
                "minIOPS": 6000,
                "maxIOPS": 8000,
                "burstIOPS": 10000
            }
        }
    ]
}
----


== Cloud Volumes Service (CVS) na configuração do GCP

O Astra Trident dá suporte a volumes com o tipo de serviço CVS padrão https://cloud.google.com/architecture/partners/netapp-cloud-volumes/service-types["GCP"^] no . O Astra Trident não dá suporte a volumes CVS inferiores a 100 GiB, independentemente do mínimo permitido pelo tipo de serviço CVS. Portanto, o Trident cria automaticamente um volume de 100 GiB se o volume solicitado for menor do que o tamanho mínimo.

Além dos valores de configuração global, ao usar o CVS no GCP, essas opções estão disponíveis.

[cols="3*"]
|===
| Opção | Descrição | Exemplo 


| `apiRegion`  a| 
Região da conta CVS (obrigatório). É a região do GCP onde esse back-end provisionará volumes.
 a| 
"us-west2"



| `projectNumber`  a| 
Número do projeto GCP (obrigatório). Pode ser encontrado na tela inicial do portal da web do GCP.
 a| 
"123456789012"



| `hostProjectNumber`  a| 
Número do projeto do host VPC compartilhado do GCP (necessário se estiver usando uma VPC compartilhada)
 a| 
"098765432109"



| `apiKey`  a| 
Chave de API para conta de serviço do GCP com função de administrador do CVS (obrigatório). É o conteúdo formatado em JSON do arquivo de chave privada de uma conta de serviço do GCP (copiado literalmente no arquivo de configuração do back-end). A conta de serviço deve ter a função netappcloudvolumes.admin.
 a| 
(conteúdo do arquivo de chave privada)



| `secretKey`  a| 
Chave secreta da conta CVS (obrigatório). Pode ser encontrado no portal da Web CVS em Definições de conta > Acesso à API.
 a| 
"padrão"



| `proxyURL`  a| 
URL do proxy se o servidor proxy precisar se conetar à conta CVS. O servidor proxy pode ser um proxy HTTP ou um proxy HTTPS. No caso de um proxy HTTPS, a validação do certificado é ignorada para permitir o uso de certificados autoassinados no servidor proxy. *Servidores proxy com autenticação ativada não são suportados*.
 a| 
"http://proxy-server-hostname/”



| `nfsMountOptions`  a| 
Opções de montagem NFS; o padrão é "-o nfsvers 3"
 a| 
"3,proto tcp,timeo-600"



| `serviceLevel`  a| 
Nível de desempenho (padrão, premium, Extreme), padrão para "padrão"
 a| 
"premium"



| `network`  a| 
A rede do GCP usada para volumes CVS, o padrão é "padrão"
 a| 
"padrão"

|===

NOTE: Se estiver usando uma rede VPC compartilhada, você deverá especificar ambos `projectNumber` e `hostProjectNumber`. Nesse caso, `projectNumber` é o projeto de serviço e `hostProjectNumber` é o projeto host.

Ao usar o CVS no GCP, essas configurações padrão de opção de volume estão disponíveis.

[cols="3*"]
|===
| Opção | Descrição | Exemplo 


| `exportRule`  a| 
Lista de acesso NFS (endereços e/ou sub-redes CIDR), o padrão é "0,0.0,0/0"
 a| 
"10,0.1,0/24,10.0.2,100"



| `snapshotDir`  a| 
Controla a visibilidade `.snapshot` do diretório
 a| 
"falso"



| `snapshotReserve`  a| 
O padrão é "" para aceitar o padrão CVS de 0
 a| 
"10"



| `size`  a| 
Tamanho do volume, padrão para "100GiB"
 a| 
"10T"

|===


=== Exemplo CVS no arquivo de configuração do GCP

[listing]
----
{
    "version": 1,
    "storageDriverName": "gcp-cvs",
    "projectNumber": "012345678901",
    "apiRegion": "us-west2",
    "apiKey": {
        "type": "service_account",
        "project_id": "my-gcp-project",
        "private_key_id": "<id_value>",
        "private_key": "
        -----BEGIN PRIVATE KEY-----
        <key_value>
        -----END PRIVATE KEY-----\n",
        "client_email": "cloudvolumes-admin-sa@my-gcp-project.iam.gserviceaccount.com",
        "client_id": "123456789012345678901",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/cloudvolumes-admin-sa%40my-gcp-project.iam.gserviceaccount.com"
    },
    "proxyURL": "http://proxy-server-hostname/"
}
----


== Configuração do Azure NetApp Files

Para configurar e usar um https://azure.microsoft.com/en-us/services/netapp/["Azure NetApp Files"^] back-end, você precisará do seguinte:

* `subscriptionID` A partir de uma subscrição do Azure com o Azure NetApp Files ativado
* `tenantID`, `clientID` E `clientSecret` de um https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal["Registo da aplicação"^] no Azure ative Directory com permissões suficientes para o serviço Azure NetApp Files
* Localização do Azure que contém pelo menos um https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-delegate-subnet["sub-rede delegada"^]



TIP: Se você estiver usando o Azure NetApp Files pela primeira vez ou em um novo local, será necessária alguma configuração inicial para que o o https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-quickstart-set-up-account-create-volumes?tabs=azure-portal["guia quickstart"^] o possa guiar.


NOTE: O Astra Trident 21.04.0 e versões anteriores não são compatíveis com pools de capacidade de QoS manual.

[cols="3*"]
|===
| Opção | Descrição | Padrão 


| `version`  a| 
Sempre 1
 a| 



| `storageDriverName`  a| 
"azure-NetApp-files"
 a| 



| `backendName`  a| 
Nome personalizado para o back-end de armazenamento
 a| 
Nome do condutor e carateres aleatórios



| `subscriptionID`  a| 
O ID da assinatura da sua assinatura do Azure
 a| 



| `tenantID`  a| 
O ID do locatário de um Registro de aplicativo
 a| 



| `clientID`  a| 
A ID do cliente de um registo de aplicação
 a| 



| `clientSecret`  a| 
O segredo do cliente de um Registro de aplicativo
 a| 



| `serviceLevel`  a| 
Um dos "Standard", "Premium" ou "Ultra"
 a| 
"" (aleatório)



| `location`  a| 
O nome do local do Azure novos volumes serão criados no
 a| 
"" (aleatório)



| `virtualNetwork`  a| 
Nome de uma rede virtual com uma sub-rede delegada
 a| 
"" (aleatório)



| `subnet`  a| 
Nome de uma sub-rede delegada `Microsoft.Netapp/volumes`
 a| 
"" (aleatório)



| `nfsMountOptions`  a| 
Controle refinado das opções de montagem NFS
 a| 
3



| `limitVolumeSize`  a| 
Falha no provisionamento se o tamanho do volume solicitado estiver acima desse valor
 a| 
"" (não aplicado por padrão)

|===

NOTE: O serviço Azure NetApp Files não oferece suporte a volumes com menos de 100 GB de tamanho. Para facilitar a implantação de aplicativos, o Trident cria automaticamente volumes de 100 GB se um volume menor for solicitado.

Você pode controlar como cada volume é provisionado por padrão usando essas opções em uma seção especial da configuração.

[cols="3*"]
|===
| Opção | Descrição | Padrão 


| `exportRule`  a| 
As regras de exportação para novos volumes. Deve ser uma lista separada por vírgulas de qualquer combinação de endereços IPv4 ou sub-redes IPv4 na notação CIDR.
 a| 
"0,0.0,0/0"



| `snapshotDir`  a| 
Controla a visibilidade `.snapshot` do diretório
 a| 
"falso"



| `size`  a| 
O tamanho padrão dos novos volumes
 a| 
"100G"

|===


=== Exemplo de configurações do Azure NetApp Files

* Exemplo 1: Configuração mínima de back-end para azure-NetApp-Files*

Esta é a configuração mínima absoluta de back-end. Com essa configuração, o Trident descobrirá todas as suas contas do NetApp, pools de capacidade e sub-redes delegadas no ANF em todos os locais do mundo e colocará novos volumes em um deles aleatoriamente.

Essa configuração é útil quando você começar a usar o ANF e experimentar as coisas, mas na prática você vai querer fornecer um escopo adicional para os volumes provisionados para garantir que eles tenham as características desejadas e acabem em em uma rede próxima da computação que está usando. Veja os exemplos subsequentes para obter mais detalhes.

[listing]
----
{
    "version": 1,
    "storageDriverName": "azure-netapp-files",
    "subscriptionID": "9f87c765-4774-fake-ae98-a721add45451",
    "tenantID": "68e4f836-edc1-fake-bff9-b2d865ee56cf",
    "clientID": "dd043f63-bf8e-fake-8076-8de91e5713aa",
    "clientSecret": "SECRET"
}
----
*Exemplo 2: Local único e nível de serviço específico para arquivos azure-NetApp*

Essa configuração de back-end coloca volumes no local "eastus" do Azure em um pool de capacidade "Premium". O Trident descobre automaticamente todas as sub-redes delegadas ao ANF nesse local e colocará um novo volume em uma delas aleatoriamente.

[listing]
----
{
    "version": 1,
    "storageDriverName": "azure-netapp-files",
    "subscriptionID": "9f87c765-4774-fake-ae98-a721add45451",
    "tenantID": "68e4f836-edc1-fake-bff9-b2d865ee56cf",
    "clientID": "dd043f63-bf8e-fake-8076-8de91e5713aa",
    "clientSecret": "SECRET",
    "location": "eastus",
    "serviceLevel": "Premium"
}
----
*Exemplo 3: Configuração avançada para arquivos azure-NetApp*

Essa configuração de back-end reduz ainda mais o escopo do posicionamento de volume para uma única sub-rede e também modifica alguns padrões de provisionamento de volume.

[listing]
----
{
    "version": 1,
    "storageDriverName": "azure-netapp-files",
    "subscriptionID": "9f87c765-4774-fake-ae98-a721add45451",
    "tenantID": "68e4f836-edc1-fake-bff9-b2d865ee56cf",
    "clientID": "dd043f63-bf8e-fake-8076-8de91e5713aa",
    "clientSecret": "SECRET",
    "location": "eastus",
    "serviceLevel": "Premium",
    "virtualNetwork": "my-virtual-network",
    "subnet": "my-subnet",
    "nfsMountOptions": "nfsvers=3,proto=tcp,timeo=600",
    "limitVolumeSize": "500Gi",
    "defaults": {
        "exportRule": "10.0.0.0/24,10.0.1.0/24,10.0.2.100",
        "size": "200Gi"
    }
}
----
*Exemplo 4: Pools de armazenamento virtual com arquivos azure-NetApp*

Essa configuração de back-end define vários link:../trident-concepts/virtual-storage-pool.html["piscinas de armazenamento"^] em um único arquivo. Isso é útil quando você tem vários pools de capacidade com suporte a diferentes níveis de serviço e deseja criar classes de storage no Kubernetes que os representem.

Isso está apenas arranhando a superfície do poder dos pools de armazenamento virtual e suas etiquetas.

[listing]
----
{
    "version": 1,
    "storageDriverName": "azure-netapp-files",
    "subscriptionID": "9f87c765-4774-fake-ae98-a721add45451",
    "tenantID": "68e4f836-edc1-fake-bff9-b2d865ee56cf",
    "clientID": "dd043f63-bf8e-fake-8076-8de91e5713aa",
    "clientSecret": "SECRET",
    "nfsMountOptions": "nfsvers=3,proto=tcp,timeo=600",
    "labels": {
        "cloud": "azure"
    },
    "location": "eastus",

    "storage": [
        {
            "labels": {
                "performance": "gold"
            },
            "serviceLevel": "Ultra"
        },
        {
            "labels": {
                "performance": "silver"
            },
            "serviceLevel": "Premium"
        },
        {
            "labels": {
                "performance": "bronze"
            },
            "serviceLevel": "Standard",
        }
    ]
}
----