---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy.html 
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator, smb, windows 
summary: 'O operador Trident permite personalizar a maneira como o Astra Trident é instalado usando os atributos na `TridentOrchestrator` especificação.' 
---
= Personalizar a implantação do operador Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O operador Trident permite personalizar a instalação do Astra Trident usando os atributos da `TridentOrchestrator` especificação.

Se você quiser personalizar a instalação além do que `TridentOrchestrator` os argumentos permitem, considere usar `tridentctl` para gerar manifestos YAML personalizados que você pode modificar conforme necessário.


WARNING: `spec.namespace` É especificado em `TridentOrchestrator` para indicar qual namespace onde o Astra Trident está instalado. Este parâmetro *não pode ser atualizado após a instalação do Astra Trident*. Tentar fazê-lo faz com que o `TridentOrchestrator` status mude para `Failed`. O Astra Trident não se destina a ser migrado entre namespaces.



== Opções de configuração

Esta tabela detalha `TridentOrchestrator` atributos:

[cols="3"]
|===
| Parâmetro | Descrição | Padrão 


| `namespace` | Namespace para instalar Astra Trident em | "predefinição" 


| `debug` | Habilite a depuração para o Astra Trident | falso 


| `windows` | A configuração para `true` permite a instalação em nós de trabalho do Windows. | falso 


| `IPv6` | Instalar o Astra Trident em IPv6 | falso 


| `k8sTimeout` | Tempo limite para operações do Kubernetes | 30sec 


| `silenceAutosupport` | Não envie pacotes AutoSupport para o NetApp automaticamente | falso 


| `enableNodePrep` | Gerenciar dependências de nó de trabalho automaticamente (*BETA*) | falso 


| `autosupportImage` | A imagem do recipiente para a telemetria AutoSupport | "NetApp/Trident-AutoSupport:22.10.0" 


| `autosupportProxy` | O endereço/porta de um proxy para o envio de telemetria AutoSupport | "http://proxy.example.com:8888"[] 


| `uninstall` | Um sinalizador usado para desinstalar o Astra Trident | falso 


| `logFormat` | Formato de log Astra Trident a ser usado [text,json] | "texto" 


| `tridentImage` | Imagem Astra Trident a instalar | "NetApp/Trident:21,04" 


| `imageRegistry` | Caminho para o Registro interno, do formato
`<registry FQDN>[:port][/subpath]` | "k8s.gcr.io/sig-storage (mais de k8s 1,19 gb) ou quay.io/k8scsi gb" 


| `kubeletDir` | Caminho para o diretório kubelet no host | "/var/lib/kubelet" 


| `wipeout` | Uma lista de recursos a serem excluídos para realizar uma remoção completa do Astra Trident |  


| `imagePullSecrets` | Segredos para extrair imagens de um Registro interno |  


| `controllerPluginNodeSelector` | Seletores de nós adicionais para pods executando o plug-in CSI controlador Trident. Segue o mesmo formato que pod.spec.nodeSelector. | Sem padrão; opcional 


| `controllerPluginTolerations` | Substitui as tolerâncias para pods que executam o plug-in CSI controlador Trident. Segue o mesmo formato que pod.spec.Tolerations. | Sem padrão; opcional 


| `nodePluginNodeSelector` | Seletores de nós adicionais para pods executando o plug-in CSI nó Trident. Segue o mesmo formato que pod.spec.nodeSelector. | Sem padrão; opcional 


| `nodePluginTolerations` | Substitui as tolerâncias para pods que executam o plug-in CSI nó Trident. Segue o mesmo formato que pod.spec.Tolerations. | Sem padrão; opcional 
|===

NOTE: Para obter mais informações sobre a formatação dos parâmetros do pod, link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["Atribuindo pods a nós"^]consulte .



== Exemplos de configurações

Você pode usar os atributos mencionados acima ao definir `TridentOrchestrator` para personalizar sua instalação.

.Exemplo 1: Configuração personalizada básica
[%collapsible%open]
====
Este é um exemplo para uma configuração personalizada básica.

[listing]
----
cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullSecrets:
  - thisisasecret
----
====
.Exemplo 2: Implante com seletores de nós
[%collapsible%open]
====
Este exemplo ilustra como o Trident pode ser implantado com seletores de nós:

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  controllerPluginNodeSelector:
    nodetype: master
  nodePluginNodeSelector:
    storage: netapp
----
====
.Exemplo 3: Implantar em nós de trabalho do Windows
[%collapsible%open]
====
Este exemplo ilustra a implantação em um nó de trabalho do Windows.

[listing]
----
$ cat deploy/crds/tridentorchestrator_cr.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  windows: true
----
====