---
sidebar: sidebar 
permalink: trident-concepts/ontap-drivers.html 
keywords: trident backend, AFF, FAS, ONTAP Select, Cloud, Amazon FSx for NetApp ONTAP, drivers, ONTAP drivers 
summary: Saiba mais sobre como criar e usar um backend Element com a instalação do Trident. 
---
= Controladores ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Astra Trident fornece cinco drivers de storage ONTAP exclusivos para comunicação com clusters ONTAP. Saiba mais sobre como cada driver lida com a criação de volumes e controle de acesso e suas capacidades.



== Saiba mais sobre os drivers de armazenamento ONTAP

[cols="5"]
|===
| Condutor | Protocolo | VolumeMode | Modos de acesso suportados | Sistemas de arquivos suportados 


| `ontap-nas`  a| 
NFS
 a| 
Sistema de ficheiros
 a| 
RWO, ROX, RWX
 a| 
"", nfs



| `ontap-nas-economy`  a| 
NFS
 a| 
Sistema de ficheiros
 a| 
RWO, ROX, RWX
 a| 
"", nfs



| `ontap-nas-flexgroup`  a| 
NFS
 a| 
Sistema de ficheiros
 a| 
RWO, ROX, RWX
 a| 
"", nfs



| `ontap-san`  a| 
ISCSI
 a| 
Bloco
 a| 
RWO, ROX, RWX
 a| 
Sem sistema de arquivos; dispositivo de bloco bruto



| `ontap-san`  a| 
ISCSI
 a| 
Sistema de ficheiros
 a| 
RWO, ROX

RWX não está disponível no modo volume do sistema de arquivos.
 a| 
`xfs` `ext3`, , `ext4`



| `ontap-san-economy`  a| 
ISCSI
 a| 
Bloco
 a| 
RWO, ROX, RWX
 a| 
Sem sistema de arquivos; dispositivo de bloco bruto



| `ontap-san-economy`  a| 
ISCSI
 a| 
Sistema de ficheiros
 a| 
RWO, ROX

RWX não está disponível no modo volume do sistema de arquivos.
 a| 
`xfs` `ext3`, , `ext4`

|===

NOTE: Os backends do ONTAP podem ser autenticados usando credenciais de login para uma função de segurança (nome de usuário/senha) ou usando a chave privada e o certificado que está instalado no cluster do ONTAP. Você pode atualizar os backends existentes para passar de um modo de autenticação para o outro com `tridentctl update backend`o .
